### ISSUE TITLE
Unexpected unknown exception from MEX file..

### ISSUE THREAD

**Issue by mobarakolislam** [BVLC/caffe#3148] opened 2015-10-05 07:35 UTC
I am getting this error while executing this command in matlab -nodisplay mode. I have lmdb data in the proper directory.
Command:
solver = caffe.Solver('./examples/mnist/lenet_solver.prototxt');

Error:
I1005 15:32:08.630614  1927 db_lmdb.cpp:23] Opened lmdb examples/mnist/mnist_train_lmdb
Unexpected unknown exception from MEX file..

Error in caffe.get_solver (line 7)
pSolver = caffe_('get_solver', solver_file);

Error in caffe.Solver (line 21)
        self = caffe.get_solver(varargin{:});

**Comment by tpet** [comment] 2015-11-18 12:26
The bug was introduced somewhere between 0d7c6cb4b2286980c3d5b47cfddb2457202c93cf (good) and 603cbfb97767d1b9ebf102200646f5df237d1749 (bad).

**Comment by mobarakolislam** [comment] 2015-12-09 06:49
Some of friends also getting same error? Is there any solution? I think it's a problem of matlab with LMDB dataset because lmdb is working fine for CPP and python. However, this error is not occuring in the Matlab 2013.

**Comment by wangjian4500** [comment] 2016-01-15 14:30
I run into the same question. And I fixed it by adding meanImage.binaryproto.Like：
  transform_param {
    mean_file: "Data/train_lmdb/mean.binaryproto"
  }

**Comment by rodrigodebem** [comment] 2016-01-26 17:08
I am having the same issue with Matlab R2014a. Someone has any idea how to fix it?

**Comment by athus1990** [comment] 2016-02-01 02:50
Hi,
I ahve the same issue as well and it happens only with fastrcnn for me

**Comment by shelhamer** [comment] 2017-04-14 02:30
Closing as likely duplicate of #3005

**Closed by shelhamer** 2017-04-14 02:30 UTC
Labels: Matlab
