### ISSUE TITLE
deconv layer from python

### ISSUE THREAD

**Issue by dolevr** [BVLC/caffe#4258] opened 2016-06-02 14:34 UTC
Hi,
When trying to create a deconvolution layer with parameters from the python interface, you receive an error when producing the proto:

...
n.deconv1 = L.Deonvolution(n.data, 
                            kernel=5, 
                            stride=2,
                            bias_term=False,
                            num_output=1, 
                            weight_filler=dict(type='xavier',std=0.01))
...
n.to_proto()

Produces:
Traceback (most recent call last):
  File "data_generator.py", line 197, in <module>
    main()
  File "data_generator.py", line 192, in main
    produce_cae(user_tmp)
  File "data_generator.py", line 176, in produce_cae
    print(cae_net('train', None, _batch_size=32, _user=1, _fold=-1, _len=24), file=f)
  File "data_generator.py", line 123, in cae_net
    return str(n.to_proto())
  File "/usr2/draviv/workspace/caffe/python/caffe/net_spec.py", line 189, in to_proto
    top._to_proto(layers, names, autonames)
  File "/usr2/draviv/workspace/caffe/python/caffe/net_spec.py", line 97, in _to_proto
    return self.fn._to_proto(layers, names, autonames)
  File "/usr2/draviv/workspace/caffe/python/caffe/net_spec.py", line 158, in _to_proto
    assign_proto(layer, k, v)
  File "/usr2/draviv/workspace/caffe/python/caffe/net_spec.py", line 64, in assign_proto
    is_repeated_field = hasattr(getattr(proto, name), 'extend')
AttributeError: 'LayerParameter' object has no attributeTraceback (most recent call last):
  File "data_generator.py", line 197, in <module>
    main()
  File "data_generator.py", line 192, in main
    produce_cae(user_tmp)
  File "data_generator.py", line 176, in produce_cae
    print(cae_net('train', None, _batch_size=32, _user=1, _fold=-1, _len=24), file=f)
  File "data_generator.py", line 123, in cae_net
    return str(n.to_proto())
  File "/usr2/draviv/workspace/caffe/python/caffe/net_spec.py", line 189, in to_proto
    top._to_proto(layers, names, autonames)
  File "/usr2/draviv/workspace/caffe/python/caffe/net_spec.py", line 97, in _to_proto
    return self.fn._to_proto(layers, names, autonames)
  File "/usr2/draviv/workspace/caffe/python/caffe/net_spec.py", line 158, in _to_proto
    assign_proto(layer, k, v)
  File "/usr2/draviv/workspace/caffe/python/caffe/net_spec.py", line 64, in assign_proto
    is_repeated_field = hasattr(getattr(proto, name), 'extend')
AttributeError: 'LayerParameter' object has no attribute 'weight_filler'

The error here is only for 'weight_filler', but it will be for any attribute.
I assume this is because the inner param block is convolution_param and not deconvolution_param:
layer {
  name: "deconv1"
  type: "Deconvolution"
  bottom: "conv1"
  top: "deconv1"
  convolution_param {
    num_output: 1
    bias_term: false
    stride: 2
    weight_filler {
      type: "xavier"
      std: 0.01
    }
    kernel: 5
  }
}

Thanks,
Dolev

**Comment by lukeyeager** [comment] 2016-06-02 16:52
You might want to take a look at how @yosinski has done it:
https://github.com/yosinski/deep-visualization-toolbox/issues/44

**Comment by shelhamer** [comment] 2016-06-02 19:15
Duplicate of #4052. @dolevr see the correct syntax there. See #3954 for a patch to make defining deconv the same as conv. Ask usage questions like this on the mailing list next time.

@lukeyeager that's actually a different deconvolution, in that case its in the sense of *deconvolution networks* and the varieties of visualization methods that have since been explored along those lines. Here it's simply a matter of defining a *deconvolution layer*.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Closed by shelhamer** 2016-06-02 19:15 UTC

**Comment by lukeyeager** [comment] 2016-06-02 19:18
> @lukeyeager that's actually a different deconvolution, in that case its in the sense of deconvolution networks and the varieties of visualization methods that have since been explored along those lines. Here it's simply a matter of defining a deconvolution layer.

Oh... yeah that makes sense. Nevermind!

**Comment by dolevr** [comment] 2016-06-05 06:48
Thanks @shelhamer ,
The behavior is unlike other layers, which raises bug suspicious in software developers.
