### ISSUE TITLE
.caffemodel constant snapshot file path 

### ISSUE THREAD

**Issue by npit** [BVLC/caffe#2281] opened 2015-04-08 12:32 UTC
It seems that the .caffemodel path is saved in the .solverstate file. 
It is impossible to move the .caffemodel to a different folder and resume training.

**Comment by shelhamer** [comment] 2015-04-08 17:56
Duplicate of #248 -- the path in the solverstate is relative.

**Closed by shelhamer** 2015-04-08 17:56 UTC
