### ISSUE TITLE
failed: shape[i] <= 0x7fffffff / count_ (50 vs. 29) blob size excezeds INT_MAX

### ISSUE THREAD

**Issue by wuqiangch** [BVLC/caffe#5185] opened 2017-01-15 13:36 UTC
when I usd hd5 file to train the caffe model,but get the error "failed: shape[i] <= 0x7fffffff / count_ (50 vs. 29) blob size excezeds INT_MAX".There are about 1.5 million images.

**Comment by shelhamer** [comment] 2017-04-14 05:50
Duplicate of #1470

**Closed by shelhamer** 2017-04-14 05:50 UTC
