### ISSUE TITLE
parse_log.sh is not up to date

### ISSUE THREAD

**Issue by thigitogatiamas** [BVLC/caffe#5453] opened 2017-03-27 18:10 UTC
When using parse_log.sh the output in the log.train is:

```
#Iters Seconds TrainingLoss LearningRate
0      6.717991     6.71804s/10  0.0005
```

This is based on the new log output which looks like this:

```
I0327 18:51:55.854897 21771 solver.cpp:219] Iteration 0 (0 iter/s, 6.71804s/10 iters), loss = 824.912
```

**Comment by shelhamer** [comment] 2017-04-12 00:46
Duplicate of #5422. Thanks for confirming.

**Closed by shelhamer** 2017-04-12 00:46 UTC
Labels: duplicate
