### ISSUE TITLE
Bad path for libcaffe.so?

### ISSUE THREAD

**Issue by kevhill** [BVLC/caffe#2723] opened 2015-07-08 22:02 UTC
Hello, trying to run caffe w/ python, installed through macports

I'm running in to the following error:
```python
ImportError: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/caffe/_caffe.so, 2): Library not loaded: @rpath/libcaffe.so
  Referenced from: /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/caffe/_caffe.so
  Reason: image not found
```

I can find libcaffe.so at `/opt/local/libexec/caffe/build/lib/libcaffe.so` so it looks like "@rpath" just needs to get mapped to "/opt/local/libexec/caffe/build/lib". Would I need to build caffe by hand to correct this or is there some more clever way?

**Comment by lukeyeager** [comment] 2015-07-08 22:08
If you use CMake and set a custom install path, the `rpath` should get set for you automatically. Give it a try!

**Comment by longjon** [comment] 2015-07-13 06:37
The `Makefile` should also set `rpath` correctly. I am no OS X expert but Google tells me there is something called `install_name_tool` that might do what you want. As this is not a bug with Caffe (and we don't maintain the macport), I'm closing this issue; continue discussion on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users).

**Closed by longjon** 2015-07-13 06:37 UTC
