### ISSUE TITLE
Error when trying to download

### ISSUE THREAD

**Issue by ANnoVector** [BVLC/caffe#6549] opened 2018-09-27 08:36 UTC
### Issue summary
I've posted in the Google Group already, but got no answer. So please excuse acting against the guidlines by posting about something installation-related on Github, but I think my issue not only originates on Github but it can also be solved quite quickly if addressed from here.

Heres what's wrong: When I try to download any version of Caffe for Windows, I get this error message:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>BlobNotFound</Code>
<Message>
The specified blob does not exist. RequestId:25dddc15-b01e-0014-0f3c-567980000000 Time:2018-09-27T08:31:51.1938828Z
</Message>
</Error>

I tried finding another source for the version I need online, but everything links back to Github (which is probably a good thing).

### Steps to reproduce
Click on one of the download links for Windows versions.

### Tried solutions
Not much to do. It is probably an issue with the hosted file.

### System configuration

* Operating system: Windows 10, Browsers: Chrome and Firefox
* Compiler: -
* CUDA version (if applicable): -
* CUDNN version (if applicable): -
* BLAS: -
* Python version (if using pycaffe): 2.7
* MATLAB version (if using matcaffe): 

### Issue checklist

- [x] read the guidelines and removed the first paragraph
- [x] written a short summary and detailed steps to reproduce
- [x] explained how solutions to related problems failed (tick if found none)
- [x] filled system configuration
- [x] attached relevant logs/config files (tick if not applicable)

**Comment by willyd** [comment] 2018-10-24 02:45
Yes prebuilt binaries links are broken. You can try the conda packages. See https://github.com/BVLC/caffe/issues/6569#issuecomment-432491851.

**Comment by willyd** [comment] 2018-10-24 02:47
Closing as duplicate of https://github.com/BVLC/caffe/issues/6529.

**Closed by willyd** 2018-10-24 02:47 UTC
Labels: windows
