### ISSUE TITLE
error  about  app.py

### ISSUE THREAD

**Issue by wzq12138** [BVLC/caffe#2103] opened 2015-03-12 02:51 UTC
I  run  the   python examples/web_demo/app.py

the  error  is  like  this
E0312 10:49:35.522589  6449 upgrade_proto.cpp:616] Note that future Caffe releases will only support transform_param messages for transformation fields.
F0312 10:49:35.604167  6449 net.cpp:713] Check failed: target_blobs[j]->height() == source_layer.blobs(j).height() (9 vs. 1000) 
*** Check failure stack trace: ***

**Comment by wzq12138** [comment] 2015-03-12 03:31
ubuntu@tegra-ubuntu:~/caffe$ python examples/web_demo/app.py 
INFO:root:Loading net and associated files...
Traceback (most recent call last):
  File "examples/web_demo/app.py", line 222, in <module>
    start_from_terminal(app)
  File "examples/web_demo/app.py", line 210, in start_from_terminal
    app.clf = ImagenetClassifier(**ImagenetClassifier.default_args)
  File "examples/web_demo/app.py", line 125, in __init__
    mean=np.load(mean_file), channel_swap=(2, 1, 0), gpu=gpu_mode
TypeError: __init__() got an unexpected keyword argument 'gpu'

**Comment by shelhamer** [comment] 2015-03-12 03:33
Duplicate of #1937 -- fix is in master from #2058.

**Closed by shelhamer** 2015-03-12 03:33 UTC
