### ISSUE TITLE
caffe Error running "make runtest" (Failed to open leveldb)

### ISSUE THREAD

**Issue by wpl18589946597** [BVLC/caffe#6431] opened 2018-06-15 04:23 UTC
F0615 04:23:12.973625 37312 db_leveldb.cpp:16] Check failed: status.ok() Failed to open leveldb 
Invalid argument: : does not exist (create_if_missing is false)
*** Check failure stack trace: ***
    @     0x7fe9afc1195d  google::LogMessage::Fail()
    @     0x7fe9afc136e0  google::LogMessage::SendToLog()
    @     0x7fe9afc11543  google::LogMessage::Flush()
    @     0x7fe9afc140ae  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fe9ad7c28a3  caffe::db::LevelDB::Open()
    @     0x7fe9ad775990  caffe::DataReader::Body::InternalThreadEntry()
    @     0x7fe9ad9280a5  caffe::InternalThread::entry()
    @     0x7fe9ae2f45d5  (unknown)
    @     0x7fe9ace786ba  start_thread
    @     0x7fe9acbae41d  (unknown)
Makefile:524: recipe for target 'runtest' failed
make: *** [runtest] Aborted (core dumped)

**Comment by Usernamezhx** [comment] 2018-06-22 03:22
I have the problem too.

**Comment by Noiredd** [comment] 2018-08-17 07:58
Duplicate of #850, closing. If there's a reason to believe that this has a different cause than that, feel free to add details and reopen.

**Closed by Noiredd** 2018-08-17 07:58 UTC

**Comment by KWAN-YWAN** [comment] 2018-09-02 05:51
I have the same problem, can you help me? thank you very much

**Comment by KWAN-YWAN** [comment] 2018-09-02 06:38
@wpl18589946597 I meet the same problem with you, how to deal with it ? can you help me?

**Comment by honorpeter** [comment] 2019-07-02 06:59
F0615 04:23:12.973625 37312 db_leveldb.cpp:16] Check failed: status.ok() Failed to open leveldb
Invalid argument: : does not exist (create_if_missing is false)
I have the same problem, can you help me? thank you very much
