### ISSUE TITLE
Unable to do forward pass with updated internal layer data in pycaffe

### ISSUE THREAD

**Issue by AndrewZhengXiao** [BVLC/caffe#5331] opened 2017-02-27 08:12 UTC
![second](https://cloud.githubusercontent.com/assets/21032479/23353245/6e13a10a-fd06-11e6-9145-a20dc635e841.png)

I'm a beginner in Caffe. And I built a model as figure shows.  My python code shows as following

`   img = caffe.io.load_image(path + filename)

    in_=np.array(img,dtype=np.float32)

    in_=in_[:,:,::-1]

    in_.transpose((2,0,1))
    net.blobs['data'].reshape(1,*in_.shape)
    net.blobs['data'].data[...] = in_
    out = net.forward(start='second', end='conv1')
    in_=np.array(img,dtype=np.float32)
    in_=in_[:,:,::-1]
    in_.transpose((2,0,1))
    net.blobs['data'].reshape(1,*in_.shape)
    net.blobs['data'].data[...] = in_
    print  net.blobs['data'].data[...]
    pridects = out['conv1']`

The problem is when I using the model been trained. The internal layer data doesn't change at all.
Which means net.blobs['data'].data[...] changes as I set it to a new image input but the output from layer conv1 doesn't change at all.  
For example, I set input  image 1 and transfer the image data to suit for data layer. With the input changed, net.blobs['data'].data[...] also changes to the same data.  But after net.forward, out['conv1'] still remain the same as trained model.

**Comment by katerakelly** [comment] 2017-03-02 02:33
I believe this is the same issue as #5026

**Comment by AndrewZhengXiao** [comment] 2017-03-03 01:54
Thanks a lot! :)

**Comment by shelhamer** [comment] 2017-03-23 03:17
Closing as duplicate of #5026 (which is still to be resolved).

**Closed by shelhamer** 2017-03-23 03:17 UTC
