### ISSUE TITLE
AttributeError: 'module' object has no attribute 'CaffeNet'

### ISSUE THREAD

**Issue by wzq12138** [BVLC/caffe#1673] opened 2015-01-04 02:19 UTC
I  have done  the  ./examples/imagenet/create_imagenet.sh      ./examples/imagenet/make_imagenet_mean.sh and  ./examples_training.sh.
and  then  I  want  to  test  this  test.py.   

#!/usr/bin/env python
"""wrapper.py implements an end-to-end wrapper that classifies an image read
from disk, using the imagenet classifier.
"""

the  error  is  that   
Traceback (most recent call last):
  File "test.py", line 110, in <module>
    net = ImageNetClassifier(MODEL_FILE, PRETRAINED)
  File "test.py", line 96, in __init__
    self.caffenet = _caffe.CaffeNet(model_def_file, pretrained_model)
AttributeError: 'module' object has no attribute 'CaffeNet'

what  did  I  do   wrong ,   can  you  help  me

**Comment by wzq12138** [comment] 2015-01-13 01:42
没人知道怎么回事吗

**Comment by shelhamer** [comment] 2015-01-15 07:46
Duplicate of #1712.

**Closed by shelhamer** 2015-01-15 07:46 UTC
Labels: duplicate
