### ISSUE TITLE
malloc(): memory corruption / SIGABRT

### ISSUE THREAD

**Issue by moi90** [BVLC/caffe#2502] opened 2015-05-22 22:15 UTC
I get the following stack trace:

```
*** Error in `/home/moi/Dokumente/Studium/Plankton/Caffe/caffe/build/tools/caffe': malloc(): memory corruption: 0x0000000000912e30 ***
*** Aborted at 1432332013 (unix time) try "date -d @1432332013" if you are using GNU date ***
PC: @     0x7fe52bad0cc9 (unknown)
*** SIGABRT (@0x3e800002996) received by PID 10646 (TID 0x7fe52cdfda40) from PID 10646; stack trace: ***
    @     0x7fe52bad0d40 (unknown)
    @     0x7fe52bad0cc9 (unknown)
    @     0x7fe52bad40d8 (unknown)
    @     0x7fe52bb0d394 (unknown)
    @     0x7fe52bb1af36 (unknown)
    @     0x7fe52bb1c7b0 (unknown)
    @     0x7fe52c8e561c caffe::SyncedMemory::mutable_cpu_data()
    @     0x7fe52c8f4163 caffe::Blob<>::mutable_cpu_diff()
    @     0x7fe52c96f7e4 caffe::InnerProductLayer<>::Backward_cpu()
    @     0x7fe52c99c3fd caffe::Net<>::BackwardFromTo()
    @     0x7fe52c99c5a1 caffe::Net<>::Backward()
    @     0x7fe52c8f1b5d caffe::Solver<>::Step()
    @     0x7fe52c8f242f caffe::Solver<>::Solve()
    @           0x407108 train()
    @           0x405651 main
    @     0x7fe52babbec5 (unknown)
    @           0x405bfd (unknown)
    @                0x0 (unknown)
```

Checkout 2c69258d510d8e7d412d2249c3e057870f141871

**Comment by flx42** [comment] 2015-05-22 23:26
Which command did you use?

**Comment by flx42** [comment] 2015-05-23 00:31
Also, is it reproducible 100% of the time?

You should build a new version with `DEBUG := 1` in `Makefile.config` to have a better stack trace.
After that, try to use `valgrind` with your command. Unless you are using LMDB, in this case it's not possible to use `valgrind`.

**Comment by moi90** [comment] 2015-05-23 09:31
I used `/build/tools/caffe train --solver=solver.prototxt`.

The problem seems reproductible, up to now it appears every time.

With `Debug := 1` I get the following error:
```
F0523 11:07:11.356552  4461 accuracy_layer.cpp:62] Check failed: label_value < num_labels (32 vs. 10) 
*** Check failure stack trace: ***
    @     0x7fdfe9025daa  (unknown)
    @     0x7fdfe9025ce4  (unknown)
    @     0x7fdfe90256e6  (unknown)
    @     0x7fdfe9028687  (unknown)
    @     0x7fdfe94e11da  caffe::AccuracyLayer<>::Forward_cpu()
    @           0x416381  caffe::Layer<>::Forward()
    @     0x7fdfe9553b0f  caffe::Net<>::ForwardFromTo()
    @     0x7fdfe95538d7  caffe::Net<>::ForwardPrefilled()
    @     0x7fdfe9553ca2  caffe::Net<>::Forward()
    @     0x7fdfe94ae517  caffe::Solver<>::Test()
    @     0x7fdfe94ae345  caffe::Solver<>::TestAll()
    @     0x7fdfe94ad41a  caffe::Solver<>::Step()
    @     0x7fdfe94ad03f  caffe::Solver<>::Solve()
    @           0x411e18  train()
    @           0x413dcc  main
    @     0x7fdfe8537ec5  (unknown)
    @           0x411219  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)
```

For testing purposes (running the program on my laptop) I set `test_iter: 10`, I suspect that is the Problem. I think Caffe should check this condition upfront and tell the user what to do instead of just crashing.

**Comment by moi90** [comment] 2015-05-23 15:17
The problem was having fewer output neurons than class labels, sorry for the buzz.

But nevertheless I expect Caffe to detect and report such conditions instead of crashing.

**Comment by flx42** [comment] 2015-06-25 17:30
I agree crashing is maybe not the most elegant solution here :)

I think you can close this issue.

**Comment by seanbell** [comment] 2015-06-26 17:18
@moi90 You could submit a pull request that makes the check message in caffe/layers/accuracy_layer.cpp:62 more informative.  The message could suggest that the error is possibly caused by having a wrong number of units in the previous layer, or that the ground truth labels have the wrong range.

**Comment by shelhamer** [comment] 2015-08-09 19:20
Closing as usage issue; however the change suggested by @seanbell is a good one to make this more clear.

**Closed by shelhamer** 2015-08-09 19:20 UTC
