### ISSUE TITLE
Caffe Pooling Layer Output Volume Calculation

### ISSUE THREAD

**Issue by taknevski** [BVLC/caffe#4781] opened 2016-09-28 03:46 UTC
Hi,
I tried supplying the deploy.prototxt file in the bvlc_googlenet model to pycaffe and the image size in this file is (10,3,224,224).  First a convolution layer with  PAD=3, stride =2, Kernel width = 7 is applied
so the output width/height from the first layer is  floor((224 - 7 + 2*3)/2) + 1 = 112 , this is as expected adn correct when I check the output volume shape in pycaffe printing the blob size. The output volume is (64,112,112).

This is input to the next maxpooling layer with parameters PAD=0; kernel width = 3, stride =2.
Now using the same formula: output height/width of pooling layer should be floor((112 -3 )/2) + 1 = 55
But the initialized params in pycaffe show the output height or width to be 56 when I print the blob shape.. Can someone calrify why this is the case. Do you use ceil instead of floor?

**Comment by shelhamer** [comment] 2016-09-28 18:46
Duplicate of #1318.

**Closed by shelhamer** 2016-09-28 18:46 UTC
