### ISSUE TITLE
classify.py not working with new caffe.Classifier

### ISSUE THREAD

**Issue by techurbanist** [BVLC/caffe#1949] opened 2015-02-24 04:59 UTC
When classifier is made in classify.py a 'gpu' argument is passed. This is not recognised by the new classifier.py init in master.

In classify.py:
```
    # Make classifier.
    classifier = caffe.Classifier(args.model_def, args.pretrained_model,
            image_dims=image_dims, gpu=args.gpu, mean=mean,
            input_scale=args.input_scale, raw_scale=args.raw_scale,
            channel_swap=channel_swap)
```
In classifier.py:
```
def __init__(self, model_file, pretrained_file, image_dims=None,
        mean=None, input_scale=None, raw_scale=None,
        channel_swap=None):
```

**Comment by shelhamer** [comment] 2015-02-25 23:09
Duplicate of #1937 -- thanks for the report.

**Closed by shelhamer** 2015-02-25 23:09 UTC
