### ISSUE TITLE
link to bvlc_alexnet and bvlc_reference_caffenet not working

### ISSUE THREAD

**Issue by raina0990** [BVLC/caffe#6865] opened 2019-11-13 04:20 UTC
### Issue summary

I am not able to download either of the above  mentioned models. It was working fine two weeks back but now when I try to download the model I get 
Downloading pre-trained CaffeNet model...
Traceback (most recent call last):
  File "../scripts/download_model_binary.py", line 74, in <module>
    frontmatter['caffemodel_url'], model_filename, reporthook)
  File "/usr/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 350, in open_http
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
IOError: [Errno socket error] [Errno 113] No route to host

It seems the connection is not there . Can anyone help?

**Comment by lutzroeder** [comment] 2019-11-15 05:44
```
~: curl http://dl.caffe.berkeleyvision.org/bvlc_alexnet.caffemodel 
curl: (52) Empty reply from server
```

**Comment by lutzroeder** [comment] 2019-11-15 05:45
Duplicate of #6864

**Closed** 2019-11-15 15:08 UTC
Labels: duplicate
