### ISSUE TITLE
Add new image categories in pre trained caffe model

### ISSUE THREAD

**Issue by apurvmmmec** [BVLC/caffe#3222] opened 2015-10-20 04:35 UTC
Hello Team

Is it possible to add some new scene categories to existing pretrained cafe model.
I am trying to use MIT Places Scene Recognition model for my use, but I want to add few more scene categories to it. I want to detect those new categories as well as the original 1000 categories which the model also detects.
I tried creating a model using NVIDIA Digits using a pre-trained model. It allowed me add new categories by adding labelled training images, but then the model is able to detect only my newly added categories and does not detect the categories which it used to detect before my modification.
Pls help in this direction.

Apurv

**Comment by RadicoLabs** [comment] 2015-10-28 11:44
I can Second this... Attempted to finetune AlexNet model with 2 additional custom categories, and for some reason, the model now only classifies the 2 custom categories, not all the pretrained-categories.... Any way to solve this?

**Comment by apurvmmmec** [comment] 2015-11-02 07:36
Any help on this will be highly appreciated !!!

**Comment by bhack** [comment] 2015-11-02 08:18
The problem is more complex. For example you can see http://arxiv.org/abs/1506.04477. Please use the Caffe mailing list for support instead.

**Comment by longjon** [comment] 2015-11-05 08:19
Closing as a request for help/usage issue.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Closed by longjon** 2015-11-05 08:19 UTC
