### ISSUE TITLE
How to Input data and labels from different lmdb files while training?

### ISSUE THREAD

**Issue by kalyanvasudev** [BVLC/caffe#2752] opened 2015-07-12 15:24 UTC
Hi,

I have separate lmdb files generated for images and labels respectively where the order of images and labels being written to lmdb files is the same. 

Now my question is how do I pass these two seprate imdb files in prototxt file? Do I need to create two different data layers? If so, will I face indexing issues (mix up between images and corresponding labels)?

Please help me out here. 
Thanks a lot!

-Kalyan

**Comment by seanbell** [comment] 2015-07-12 16:15
Duplicate of #2751

**Closed** 2015-07-13 06:09 UTC
