### ISSUE TITLE
check failed: -mkdir(source.c_str())==0 (-1 vs. 0) mkdir    failed

### ISSUE THREAD

**Issue by NaveenBandi** [BVLC/caffe#6096] opened 2017-12-08 04:18 UTC
While I am creating lmdb using create_imagenet.sh in windows. I get this error. The code is finding the images to created to lmdb. But fails while creating the directory. I have set the path as shown in the figure. 
Please suggest.

### Your system configuration
Operating system:windows 7
Compiler:cl.exe
CUDA version (if applicable):
CUDNN version (if applicable):
BLAS:open
Python or MATLAB version (for pycaffe and matcaffe respectively):pycaffe
![failure](https://user-images.githubusercontent.com/23726777/33750851-bc28a37e-dbfc-11e7-9c78-4133462db768.JPG)
![path](https://user-images.githubusercontent.com/23726777/33750871-d9856380-dbfc-11e7-9967-88c54d3bc2d0.JPG)

**Comment by Noiredd** [comment] 2017-12-08 07:01
Closing as this is a duplicate of a [question](https://groups.google.com/forum/#!topic/caffe-users/7jMCb-4u2Hk) posted on the user list. Please reply in that thread instead.

**Closed by Noiredd** 2017-12-08 07:01 UTC

**Comment by richardharmadi** [comment] 2018-04-04 05:26
don't make the last folder.

For example:
if your path is /root/caffe/data/imageset/lmdb/trainval_lmdb
create up to lmdb folder manually but not the trainval_lmdb
