### ISSUE TITLE
top_k parameter doesn't take any effect

### ISSUE THREAD

**Issue by cysin** [BVLC/caffe#3280] opened 2015-11-04 08:12 UTC
top_k parameter doesn't take any effect in ArgMax layer, could someone have a review on argmax_layer.cpp? There's definitely a bug, there is a line:

```
shape[2] = top_k_;
```
and shape was initialized with std::vector<int> shape(bottom[0]->num_axes(), 1)
and sometimes shape was only with size = 2!

**Comment by longjon** [comment] 2015-11-05 06:34
Thanks for the report, I'm closing as a duplicate of #3274.

**Closed by longjon** 2015-11-05 06:34 UTC
