### ISSUE TITLE
CUDNN: release 2

### ISSUE THREAD

**Issue by Felix-neko** [BVLC/caffe#1715] opened 2015-01-13 18:34 UTC
There has released a new version of CUDNN. nVidia guys say that its performance has greatly boosted.

Alas, the API has changed a bit, and we cannot just use the newer version.

**Is it planned to support CUDNN R2?**

**Comment by bhack** [comment] 2015-01-13 18:48
Please close this. It is a duplicate of https://github.com/BVLC/caffe/issues/1622

**Closed** 2015-01-13 19:53 UTC
Labels: duplicate
