### ISSUE TITLE
Makefile:533: recipe for target 'runtest' failed

### ISSUE THREAD

**Issue by felix-liuying** [BVLC/caffe#6260] opened 2018-02-27 06:19 UTC
when i install caffe ,make all  ,make test  successfully,but make runtest failed

### Issue summary
[  PASSED  ] 2138 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] BatchReindexLayerTest/3.TestGradient, where TypeParam = caffe::GPUDevice<double>

 1 FAILED TEST
Makefile:533: recipe for target 'runtest' failed
make: *** [runtest] Error 1

### Steps to reproduce

cuda9.1+cudnn_v7+opencv3.4+caffe+anaconda2

### Your system configuration
Operating system:ubutu16.04.3
Compiler:
CUDA version (if applicable):9.1
CUDNN version (if applicable):v7
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):pycaffe2.7.14(anaconda)

**Comment by Noiredd** [comment] 2018-02-27 07:20
Duplicate of #6164

**Closed by Noiredd** 2018-02-27 07:20 UTC
Labels: duplicate

**Comment by Darcy-z** [comment] 2018-04-19 00:58
I have the same problem. Have you solved it?
