### ISSUE TITLE
Prebuilt binaries cannot be downloaded

### ISSUE THREAD

**Issue by kalnkaya** [BVLC/caffe#6529] opened 2018-09-06 03:18 UTC
Prebuilt binaries cannot be downloaded.

**Comment by willyd** [comment] 2018-10-24 02:48
Yes prebuilt binaries links are broken. You can try the conda packages. See https://github.com/BVLC/caffe/issues/6569#issuecomment-432491851.

**Comment by willyd** [comment] 2018-10-24 02:50
Closing as duplicate of https://github.com/BVLC/caffe/issues/6483.

**Closed by willyd** 2018-10-24 02:50 UTC
