### ISSUE TITLE
attributeError : 'module' object has no attribute 'set_random_seed'

### ISSUE THREAD

**Issue by Johnson-yue** [BVLC/caffe#3711] opened 2016-02-24 06:06 UTC
hello,everyone,
I compiled caffe-py, and I run fast-rcnn model successfully. But  when I will try to train myself net, the error appeared. 

**    File "tools/train_net.py",line78,in <module>
        caffe.set_random_seed(cfg.RNG_SEED)
AttributeError : 'module' object has no attribute 'set_random_seed'**

I don`t know why  .And I test whether caffe.set_mode_gpu() can work , it worked obviously

**Comment by lantuzi** [comment] 2016-02-25 01:34
I have the exactly same problem. Have not found solution. I am using python under windows. Is it caused by that?

**Comment by seanbell** [comment] 2016-02-25 15:54
Are you using the correct version of `caffe`?  It should be there: https://github.com/rbgirshick/caffe-fast-rcnn/blob/bcd9b4eadc7d8fbc433aeefd564e82ec63aaf69c/python/caffe/__init__.py#L2

You need to use https://github.com/rbgirshick/caffe-fast-rcnn with fast-rcnn.

Since this issue is with that codebase, and not BVLC caffe, I am closing this issue.

**Closed by seanbell** 2016-02-25 15:54 UTC
