### ISSUE TITLE
Check failed: status == CURAND_STATUS_SUCCESS (201 vs. 0)  CURAND_STATUS_LAUNCH_FAILURE

### ISSUE THREAD

**Issue by 3bobo** [BVLC/caffe#6331] opened 2018-04-04 14:06 UTC
### Issue summary
I  compiled caffe successfully,but when I run "make runtest ",there is an error "Check failed: status == CURAND_STATUS_SUCCESS (201 vs. 0)  CURAND_STATUS_LAUNCH_FAILURE",I ignored it and the mnists example is passed,but today I use nvidia-digits,when I want to train a model,the error occurs again,so the process is failed.how to fix this problem?

### Your system configuration
Ubuntu 16.04
cuda-8.0
cudnn-7.1.2
python-2.7
GPU:1050ti

**Comment by Noiredd** [comment] 2018-04-06 10:40
Duplicate of #5195

**Closed by Noiredd** 2018-04-06 10:40 UTC
