### ISSUE TITLE
Usage of MVN

### ISSUE THREAD

**Issue by hyojinie** [BVLC/caffe#3175] opened 2015-10-10 21:39 UTC
I think there is no documentation for mvn layer. I posted similar question on caffe-users few days ago, but got no response. I am trying to use mvn layer on top of fc7 in the Caffenet. It outputs ALL ZEROS no matter what I feed (i printed its output). Is my usage wrong?
...
layer {
  name: "relu7"
  type: "ReLU"
  bottom: "fc7"
  top: "fc7"
}
layer {
  name: "nfeat"
  type: "MVN"
  bottom: "fc7"
  top: "nfeat"
}

**Comment by hyojinie** [comment] 2015-10-10 23:04
For example, if I add followings before the loss layer in the examples/siamse/mnist_siamese_train_test.prototxt, and print dist_sq.cpu_data()[i], it is always 0, too.

layer {
  name: "mvn"
  type: "MVN"
  bottom: "feat"
  top: "feat"
}
layer {
  name: "mvn_p"
  type: "MVN"
  bottom: "feat_p"
  top: "feat_p"
}

**Comment by longjon** [comment] 2015-11-05 09:11
Closing as this looks like a usage issue/request for help; sorry if you did not get a response on caffe-users, but that does not change the purpose of this tracker.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Closed by longjon** 2015-11-05 09:11 UTC

**Comment by weichengkuo** [comment] 2015-11-22 22:26
I had the same issue and it was fixed by making sure the input to the MVN layer is a 4D blob.

**Comment by hello-liang** [comment] 2019-12-09 05:56
I think the problem is the output of MVN is 4D blob ,and it is used for image preprocess ,so ,if use it for vector normalize ,means input is 2D ,we need set something ,or find other layer . have you solve this problem? @hyojinie
