### ISSUE TITLE
Installing Caffe Windows

### ISSUE THREAD

**Issue by filipendo125** [BVLC/caffe#4935] opened 2016-11-01 02:15 UTC
Hi!
I have tried literally everything to run install Caffe and it still does not work.

1) I tried running everything through command line:
         Tried 
                   _call "%VS120COMNTOOLS%..\..\VC\vcvarsall.bat" amd64 (tried with VS140)
                   set CMAKE_GENERATOR=Ninja_      
                but I am getting this in both cases:

`The procedure entry point _CrtDbgReportW could not be located in the dynamic library C:\Windows\System32\MSVCP120D.dll`
 `The procedure entry point _CrtDbgReportW could not be located in the dynamic library C:\XXX\caffe-windows\libraries\bin\protoc.exe`

2)Tried VS2015 after adding CommonSettings.props :

`                Unable to read the project file "libcaffe.vcxproj" (42,5): The Imported project XXX\MSBuild\Microsoft.Cpp\v4.0\V140\BuildCustomization\Cuda7.5.props" was not found. `

Where could that file by if it isn't there?

**Comment by willyd** [comment] 2016-11-01 13:30
@filipendo125 Can you provide a detailed list of steps that will reproduce the behavior you are reporting? Something like a batch file. If using VS 2015 you need to download the right precompiled libraries by using the --msvc_version switch. See #4939 for more details.

**Comment by halimacc** [comment] 2016-11-06 07:39
@filipendo125 in addition to @willyd 's advice, with VS140 you should use 
`call "%VS140COMNTOOLS%....\VC\vcvarsall.bat" amd64`  instead.

**Comment by filipendo125** [comment] 2016-11-06 19:46
Oh sorry, I have been really busy.

@halimacc I have adjusted that accordingly before.

@willyd I have tried again using #4939, but the problem persists it doesn't recognize CUDA version that I have, although it is correct. Severity	Code	Description	Project	File	Line	Suppression State

> Error	MSB4019	The imported project "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\BuildCustomizations\CUDA 7.5.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.	libcaffe\libcaffe.vcxproj		

I know that the version is 8.0, but I have downgraded for now.

Anway, this error does not occur when I run it on VS2013, but in there I get loads of OpenCV errors.

**Comment by willyd** [comment] 2016-11-06 20:48
@filipendo125 The CMake build does not depend on the MSBuild customizations for CUDA. My guess is that you are not using the right project files. DO NOT use the project files in the `windows` folder I only left them there for reference. Instead use the ones that are created by CMake in your build folder.

**Comment by filipendo125** [comment] 2016-11-24 18:41
Right, that was the actual solution that I was looking for. Cheers.

**Comment by willyd** [comment] 2016-11-24 19:06
@filipendo125 Please close the issue if the problem is solved.

**Closed** 2016-11-24 23:35 UTC
Labels: windows
