### ISSUE TITLE
Error with nvcc

### ISSUE THREAD

**Issue by Droom1995** [BVLC/caffe#2728] opened 2015-07-09 19:12 UTC
I'm trying to install caffe, and "make all" command crashes on this line:

NVCC src/caffe/layers/inner_product_layer.cu
make: /usr/local/cuda/bin/nvcc: Command not found
make: *** [.build_release/cuda/src/caffe/layers/inner_product_layer.o] Error 127

I therefore tried to change path of CUDA to /usr, and got this mistake:

NVCC src/caffe/layers/inner_product_layer.cu
nvcc fatal   : Unsupported gpu architecture 'compute_50'
make: *** [.build_release/cuda/src/caffe/layers/inner_product_layer.o] Error 255

Any suggestions?

**Comment by seanbell** [comment] 2015-07-10 06:17
This Makefile.config comment might be helpful: https://github.com/BVLC/caffe/blob/master/Makefile.config.example#L21

**Comment by longjon** [comment] 2015-07-13 06:23
@seanbell is right; upgrade your CUDA or comment out the relevant lines of the `Makefile` to build supported architectures. Closing as this is not a bug with caffe.

**Closed by longjon** 2015-07-13 06:23 UTC

**Comment by MounirB** [comment] 2018-06-14 13:34
You should find in your system the correct link to cuda
