### ISSUE TITLE
Install CAFFE globally with root access

### ISSUE THREAD

**Issue by prathmeshrmadhu** [BVLC/caffe#4302] opened 2016-06-13 11:34 UTC
Hi,

I want to install CAFFE globally on the system. The goal is that CAFFE once installed can be accessed by other users in their own account created on the server. Please guide.

**Comment by lukeyeager** [comment] 2016-06-14 18:10
Duplicate of https://github.com/BVLC/caffe/issues/3925

**Closed** 2016-06-14 18:40 UTC
