### ISSUE TITLE
Caffe Installation - Make test

### ISSUE THREAD

**Issue by Samitha2** [BVLC/caffe#3245] opened 2015-10-26 06:21 UTC
Hi,

At the moment I am installing Caffe with GPU (GTX 590) support. I have installed the dependencies and the CUDA 7 library with the cuDNN files copied to it. However, in the compilation stage,
make all     --> runs fine
but when I run,
make test  --> the following issue is occured

```
CXX/LD -o .build_release/test/test_all.testbin src/caffe/test/test_caffe_main.cpp
.build_release/lib/libcaffe.so: undefined reference to `caffe::curandGetErrorString(curandStatus)'
.build_release/lib/libcaffe.so: undefined reference to `caffe::BaseConvolutionLayer<double>::weight_gpu_gemm(double const*, double const*, double*)'
.build_release/lib/libcaffe.so: undefined reference to `caffe::BaseConvolutionLayer<double>::forward_gpu_bias(double*, double const*)'
.build_release/lib/libcaffe.so: undefined reference to `caffe::BaseConvolutionLayer<float>::forward_gpu_bias(float*, float const*)'
.build_release/lib/libcaffe.so: undefined reference to `caffe::BaseConvolutionLayer<float>::backward_gpu_gemm(float const*, float const*, float*)'
.build_release/lib/libcaffe.so: undefined reference to `caffe::cublasGetErrorString(cublasStatus_t)'
.build_release/lib/libcaffe.so: undefined reference to `caffe::BaseConvolutionLayer<double>::forward_gpu_gemm(double const*, double const*, double*, bool)'
.build_release/lib/libcaffe.so: undefined reference to `caffe::BaseConvolutionLayer<double>::backward_gpu_gemm(double const*, double const*, double*)'
.build_release/lib/libcaffe.so: undefined reference to `caffe::BaseConvolutionLayer<double>::backward_gpu_bias(double*, double const*)'
.build_release/lib/libcaffe.so: undefined reference to `caffe::BaseConvolutionLayer<float>::forward_gpu_gemm(float const*, float const*, float*, bool)'
.build_release/lib/libcaffe.so: undefined reference to `caffe::BaseConvolutionLayer<float>::weight_gpu_gemm(float const*, float const*, float*)'
.build_release/lib/libcaffe.so: undefined reference to `caffe::BaseConvolutionLayer<float>::backward_gpu_bias(float*, float const*)'
collect2: error: ld returned 1 exit status
make: *** [.build_release/test/test_all.testbin] Error 1.
```

Could you please help me to sort this out?

**Comment by longjon** [comment] 2015-11-05 07:52
Closing as this looks like a request for help/inconsistent build state issue. Feel free to open a new issue if you can reproduce a problem with a virgin Caffe master.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Closed by longjon** 2015-11-05 07:52 UTC
