### ISSUE TITLE
Inefficient Snapshotting of Shared Parameters

### ISSUE THREAD

**Issue by mhauskn** [BVLC/caffe#2375] opened 2015-04-27 16:43 UTC
Shared parameters in Caffe are duplicated when snapshotting a model, resulting in large snapshots containing redundant information.

Example snapshot with shared convolution layers: Identical blob data is written to disk despite shared weight/bias params.

```
layer {
  name: "conv1_0"
  type: "Convolution"
  bottom: "frames_0"
  top: "conv1_0"
  param {
    name: "conv1_w"
    decay_mult: 1
  }
  param {
    name: "conv1_b"
    decay_mult: 0
  }
  blobs {
    data: -0.012329279
    data: 0.011813422
    data: -1.487906e-05
    data: 0.0090996763
    ...
}

layer {
  name: "conv1_1"
  type: "Convolution"
  bottom: "frames_1"
  top: "conv1_1"
  param {
    name: "conv1_w"
    decay_mult: 1
  }
  param {
    name: "conv1_b"
    decay_mult: 0
  }
  blobs {
    data: -0.012329279
    data: 0.011813422
    data: -1.487906e-05
    data: 0.0090996763
    ...
}
```

**Comment by shelhamer** [comment] 2015-04-27 17:25
Thanks for the report, but this is a duplicate of #1211 and #2006. This can be fixed by improving the logic for serializing the model.

**Closed by shelhamer** 2015-04-27 17:25 UTC
Labels: duplicate
