### ISSUE TITLE
caffe.berkeleyvision.org is down

### ISSUE THREAD

**Issue by djl11** [BVLC/caffe#5008] opened 2016-11-21 17:04 UTC
Sorry if this is the wrong place to query, but does anyone know when the installation instruction page can expect to be up and running again? Or there is this just a problem from my end?

This is the link I'm following: http://caffe.berkeleyvision.org/installation.html

Will delete this issue as soon as it is resolved.

Thanks,
Dan

**Comment by ClarkZinzow** [comment] 2016-11-21 17:19
The [home page](http://caffe.berkeleyvision.org/) is not working for me right now, and the installation page seems to be down intermittently.

If you don't want to wait until the page is back up, [here](http://webcache.googleusercontent.com/search?q=cache:http://caffe.berkeleyvision.org/installation.html) is a cached view of the page from three days ago.

**Comment by djl11** [comment] 2016-11-21 17:27
Great, thank you very much!
Sorry to be a pain, but you don't happen to have a similar cached view of the ubuntu specific installation page do you?
(Personally know little about .html and caching etc.)
Otherwise no problem, I shall just have to wait until it's up again!

**Comment by ClarkZinzow** [comment] 2016-11-21 18:15
@djl11 if you still want the Ubuntu specific installation page:

- [Google's cached view from November 6th](http://webcache.googleusercontent.com/search?q=cache:http://caffe.berkeleyvision.org/install_apt.html)
- [WebArchive cached view from October 18th](http://web.archive.org/web/20161018033804/http://caffe.berkeleyvision.org/install_apt.html)
 - Per @lukeyeager's great point, you can also check out the [docs in the repo](https://github.com/BVLC/caffe/blob/master/docs/install_apt.md)
 - Other resources that could be useful:  [Some notes on installing Caffe on Ubuntu,](https://gist.github.com/titipata/f0ef48ad2f0ebc07bcb9) [guide for installing Caffe on Ubuntu 16.04 or 15.10 with Cuda Toolkit 8.0, CUDNN 5.1 library and OpenCV version 2 or 3](https://github.com/BVLC/caffe/wiki/Ubuntu-16.04-or-15.10-Installation-Guide)

Also, in case you ever want to access a cached version of a website in the future, I've found the following two websites extremely helpful!

- [http://cachedview.com/](http://cachedview.com/)
- [http://www.viewcached.com/](http://www.viewcached.com/)

I hope this helps!

**Comment by djl11** [comment] 2016-11-21 18:18
Very much so! Thank you both!

**Comment by shelhamer** [comment] 2016-11-21 19:25
It seems like github pages for caffe.berkeleyvision.org went haywire briefly, but pushing to gh-pages again seems to have triggered a re-build or otherwise fixed it. The site is back now.

**Comment by farazfazli** [comment] 2016-11-22 17:25
@shelhamer It's down again.

**Comment by shelhamer** [comment] 2016-11-22 19:37
We're looking into it. It seems to be a github issue that we're hoping will be resolved soon.

As mentioned by @lukeyeager, the entire site is available at https://github.com/BVLC/caffe/tree/master/docs though not in rendered form.

**Comment by shelhamer** [comment] 2016-11-23 00:25
Github confirmed there was an intermittent issue with pages, but tells us that it should now be resolved. Closing.

**Closed by shelhamer** 2016-11-23 00:25 UTC
