### ISSUE TITLE
CUDNN Error

### ISSUE THREAD

**Issue by melgor** [BVLC/caffe#2235] opened 2015-03-31 11:19 UTC
I start learning GoogLeNet with input 96x96 (I change average pooling to 3 and add one FL layer). Unfortunetly CUDNN error occur:
<code>
F0331 13:10:30.605763 28656 cudnn_conv_layer.cu:53] Check failed: status == CUDNN_STATUS_SUCCESS (3 vs. 0)  CUDNN_STATUS_BAD_PARAM
</code>
If I change engine to "CAFFE", everything works.
Log info and model definition can be found here: https://gist.github.com/melgor/100dcee5eba7fbb2b074

I have made test with original ImageNet database and everything works. I think it is maybe about padding or other non-standard option for convolutions.

**Comment by stas-sl** [comment] 2015-04-01 14:28
I had the same issue. I think the issue is because **inception_5a** gets input of size **3x3** pixels (after several pooling layers), but contains convolution with kernel **5x5**:

```
I0331 13:10:30.168797 28656 net.cpp:120] Top shape: 64 48 3 3 (27648)
I0331 13:10:30.168802 28656 layer_factory.hpp:74] Creating layer inception_5b/5x5
I0331 13:10:30.168820 28656 net.cpp:84] Creating Layer inception_5b/5x5
```

As a workaround you can modify model definition removing some pooling layers or changing stride from 2 to 1 in the first 7x7 convolution layer.

**Comment by melgor** [comment] 2015-04-01 15:07
@stas-sl  you can have right. 
Theoretical, we can not apply 5x5 kernel to 3x3 input. But this not explain why this network works with "engine: Caffe" and its learns quite good.  I have meet several times the error like you say, but it inform about wrong dimensions. I need to investigate more deeply

**Comment by longjon** [comment] 2015-05-08 03:54
Closing as this seems to be a usage issue; ask on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) list. You're welcome to open a new issue if you are still seeing specific incorrect behavior, e.g., changing only `engine: CAFFE` to `engine: CUDNN` results in a crash with the latest `master` in `DEBUG` mode and cuDNN R2.

**Closed by longjon** 2015-05-08 03:54 UTC

**Comment by GoGoStudio** [comment] 2015-06-26 18:03
@melgor
We can apply 5x5 kernel to 3x3 input if you pad the input with border width 2.
I do not think this is an user issue. I just updated my cuDNN version and had the same issue. It seems that cuDNN R2 does not handle padding correctly.
