### ISSUE TITLE
Standardizing calculation of output activation size (for conv and pooling layers)

### ISSUE THREAD

**Issue by forresti** [BVLC/caffe#3656] opened 2016-02-09 22:51 UTC
A question:
Would it break anyone's code if we standardize the activation calculation for conv and pooling layers?

Let me show you what I mean...
conv_layer.cpp:
  `const int output_dim = (input_dim + 2 * pad_data[i] - kernel_extent) / stride_data[i] + 1;`

pooling_layer.cpp:
  `pooled_height_ = static_cast<int>(ceil(static_cast<float>( height_ + 2 * pad_h_ - kernel_h_) / stride_h_)) + 1;`

In the conv layer, the output activation size is computed using **ints**, so numbers get are rounded down. 
In the pooling layer, the output activation size is computed with a ceiling and a **float** cast around some of the math, so things are sometimes rounded up.

For example:
- input: 28x28
- 3x3 window, stride=2
- pad=1
- conv output: **15x15**
- pool output: **14x14**

This is a problem when we want to do things like concatenating 3x3/stride2 **pooling** activations with 3x3/stride2 **conv** activations, as in GoogLeNet-v2 and GoogleNet-v3.

Back to the question at the top of the post... could we standardize the calculation of activation size for conv and pooling layers? 
I'd be happy to make the appropriate PR to change this.

**Comment by seanbell** [comment] 2016-02-09 23:12
This is a long-standing discussion -- see #1318 and #3057.

**Comment by forresti** [comment] 2016-02-09 23:21
@seanbell Thanks for the pointers to the previous issues on this.

I think #3057 is a good way to enable this functionality while preserving the dimensions of existing DNN architectures. @longjon, you asked if the issue is resolved... I think #3057 is a good answer.

**Comment by shelhamer** [comment] 2016-09-09 22:54
Closing as duplicate of #1318.

**Closed by shelhamer** 2016-09-09 22:54 UTC
Labels: duplicate
