### ISSUE TITLE
C++ classification fails with OpenCV 3

### ISSUE THREAD

**Issue by Austriker** [BVLC/caffe#3282] opened 2015-11-04 15:08 UTC
Hi,

The compilation fails when it tries to build the cpp classification example with OpenCV 3 

Some functions are deprecated in OpenCV 3 for example : CV_BGR2GRAY it should be cv::COLOR_BGRA2GRAY

https://groups.google.com/d/msg/caffe-users/mZDi02lgcj0/71W9rNWs5KwJ

```
CXX examples/cpp_classification/classification.cpp
examples/cpp_classification/classification.cpp:194:31: error: use of undeclared identifier 'CV_BGR2GRAY'
    cv::cvtColor(img, sample, CV_BGR2GRAY);
                              ^
examples/cpp_classification/classification.cpp:196:31: error: use of undeclared identifier 'CV_BGRA2GRAY'
    cv::cvtColor(img, sample, CV_BGRA2GRAY);
                              ^
examples/cpp_classification/classification.cpp:198:31: error: use of undeclared identifier 'CV_BGRA2BGR'
    cv::cvtColor(img, sample, CV_BGRA2BGR);
                              ^
examples/cpp_classification/classification.cpp:200:31: error: use of undeclared identifier 'CV_GRAY2BGR'
    cv::cvtColor(img, sample, CV_GRAY2BGR);
                              ^
4 errors generated.
make: *** [.build_release/examples/cpp_classification/classification.o] Error 1
```

**Comment by flx42** [comment] 2015-11-04 15:43
See #2693 
But I'm puzzled by the fact that it compiles fine for me.

**Comment by ZhangXinNan** [comment] 2015-11-05 03:05
I think maybe you can "#define CV_BGR2GRAY cv::COLOR_BGRA2GRAY "

**Comment by longjon** [comment] 2015-11-05 06:44
Closing as a duplicate of #2693.

**Closed by longjon** 2015-11-05 06:44 UTC

**Comment by hamza-alsawy** [comment] 2019-08-14 17:12
Thanks .. that one work, 
so what about 
cv::namedWindow("imgOriginal", cv::WINDOW_AUTOSIZE);    
cv::namedWindow("imgCanny", WINDOW_AUTOSIZE); // error 
or 
cv::namedWindow("imgOriginal", WINDOW_AUTOSIZE);  //error   
cv::namedWindow("imgCanny", WINDOW_AUTOSIZE);

what actually that means, I have limited info about C++

**Comment by Antimatterr** [comment] 2020-04-28 07:58
No it's not working
i have tried BGRA2GRAY and RGB2GRAY is already wrong
