### ISSUE TITLE
In-place operation + top blob reuse in backprop

### ISSUE THREAD

**Issue by andrei-pokrovsky** [BVLC/caffe#2853] opened 2015-08-04 01:16 UTC
Hi, i was wondering what the specification is for in-place operation combined with forward top blob intermediate results reuse in backpropagation?

For instance Caffe's implementation of LRN reuses it's forward computation to perform the gradient computation. However if we attach, say an in-place ReLU on top of LRN layer output, my understanding is it will overwrite those values, which will in turn make the backprop computation incorrect.

What's the official stance/specification for this potential issue? (Unless i'm missing something?)

**Comment by seanbell** [comment] 2015-08-04 01:51
My understanding is that right now there is no specification -- you basically need to study the layer implementation to decide whether or not you can put an in-place layer after it.  Getting it wrong will lead to incorrect results, but you won't get any error or warning about it.

A better solution would be to have each layer declare whether or not it allows for in-place computation, as well as whether the *next* layer can have in-place computation.  Then, caffe could check these flags and raise errors as necessary.

**Comment by shelhamer** [comment] 2017-04-14 02:21
Duplicate of #2015.

**Closed by shelhamer** 2017-04-14 02:21 UTC
