### ISSUE TITLE
922 for HDF5

### ISSUE THREAD

**Issue by sammoes** [BVLC/caffe#4242] opened 2016-05-31 07:52 UTC
Issue 922 but for HDF5

I change the name of the data layer, but caffe quits with an error mentioning the old name.

The NetState phase (0) differed from the phase (1) specified by a rule in layer... etc.

**Comment by seanbell** [comment] 2016-05-31 12:44
Issue #922? That looks like something else.

Can you provide more information?  From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> When reporting a bug, it's most helpful to provide the following information, where applicable:
> 
> * What steps reproduce the bug?
> * Can you reproduce the bug using the latest [master](https://github.com/BVLC/caffe/tree/master), compiled with the `DEBUG` make option?
> * What hardware and operating system/distribution are you running?
> * If the bug is a crash, provide the backtrace (usually printed by Caffe; always obtainable with `gdb`).

**Comment by seanbell** [comment] 2016-05-31 12:50
I'm closing this since it sounds like a usage problem.  If you found a bug in caffe, please re-open an issue with specific steps of how to reproduce it.  Otherwise, please follow up on the mailing list if you have questions about how to use caffe.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Closed by seanbell** 2016-05-31 12:50 UTC

**Comment by sammoes** [comment] 2016-06-07 05:49
I am following the correct procedure. It is the same bug. Don't have time.
