### ISSUE TITLE
something wrong with tools/extra/plot_training_log.py.example

### ISSUE THREAD

**Issue by HALO-04** [BVLC/caffe#5361] opened 2017-03-06 12:27 UTC
when i use tools/extra/plot_training_log.py.example,  i got 
`
./tools/extra/plot_training_log.py.example 6 examples/mnist/log/save.png examples/mnist/log/my.log 
Traceback (most recent call last):
  File "./tools/extra/plot_training_log.py.example", line 191, in <module>
    plot_chart(chart_type, path_to_png, path_to_logs)
  File "./tools/extra/plot_training_log.py.example", line 117, in plot_chart
    data = load_data(data_file, x, y)
  File "./tools/extra/plot_training_log.py.example", line 88, in load_data
    data[1].append(float(fields[field_idx1].strip()))
ValueError: invalid literal for float(): 0.0845537s/100
`
could you tell me how to fix that, thx

**Comment by kimseonho** [comment] 2017-03-19 02:33
I want to solve this too..

**Comment by astroli** [comment] 2017-03-23 11:26
parse_log.sh
Line 42
grep ', loss = ' $1 | awk '{print $13}' > aux1.txt

format changed 
from "solver.cpp:228] Iteration 2000, loss = 5.99603"
to "solver.cpp:219] Iteration 104 (0.834028 iter/s, 9.592s/8 iters), loss = 0.421879"

**Comment by shelhamer** [comment] 2017-04-12 00:46
Thanks for reporting this first. Closing as duplicate of #5422 as it is more detailed.

**Closed by shelhamer** 2017-04-12 00:46 UTC
