### ISSUE TITLE
Is the latest test_gradient_based_solver.cpp correct?

### ISSUE THREAD

**Issue by chengwang777** [BVLC/caffe#3017] opened 2015-09-03 11:47 UTC
[==========] 240 tests from 24 test cases ran. (39746 ms total)
[  PASSED  ] 170 tests.
[  FAILED  ] 70 tests, listed below:
[  FAILED  ] SGDSolverTest/2.TestLeastSquaresUpdate, where TypeParam = caffe::GPUDevice<float>
[  FAILED  ] SGDSolverTest/2.TestLeastSquaresUpdateLROneHundredth, where TypeParam = caffe::GPUDevice<float>
[  FAILED  ] SGDSolverTest/2.TestLeastSquaresUpdateWithWeightDecay, where TypeParam = caffe::GPUDevice<float>
[  FAILED  ] SGDSolverTest/2.TestLeastSquaresUpdateWithWeightDecayMultiIter, where TypeParam = caffe::GPUDevice<float>
[  FAILED  ] SGDSolverTest/2.TestLeastSquaresUpdateWithMomentum, where TypeParam = caffe::GPUDevice<float>
[  FAILED  ] SGDSolverTest/2.TestLeastSquaresUpdateWithMomentumMultiIter, where TypeParam = caffe::GPUDevice<float>
[  FAILED  ] SGDSolverTest/2.TestLeastSquaresUpdateWithEverything, where TypeParam = caffe::GPUDevice<float>
...

All tests from test_gradient_based_solver.cpp is failed. What can I do?
I havd run caffe-rc, and all passed.What's the problem?

**Comment by chengwang777** [comment] 2015-09-06 08:06
I still have the problem. 
    int available_devices = 1;
#ifndef CPU_ONLY
    /*if (Caffe::mode() == Caffe::GPU) {
      CUDA_CHECK(cudaGetDeviceCount(&available_devices));
    }*/
#endif

if I comment the code above, then all tests is passed. 
I think if I have only 1 device,all is right.
But I have 4 device, then 66 tests is failed. What can I do?

**Comment by fuckcraft** [comment] 2016-07-08 11:31
I also encounter this problem,and there are 16 GPUs in my computer .I have got 70 failed in make runtest. I have already done like this ,set "export CUDA_VISIBLE_DEVICES=0",and instead EXPECT_EQ with EXPECT_NEAR and 1e-4 ,but it does not work!Still showed "src/caffe/test/test_gradient_based_solver.cpp:370: Failure
src/caffe/test/test_gradient_based_solver.cpp:378: Failure"
If you got some methods to deal with these problems,Please notice me,thank you!

**Comment by fuckcraft** [comment] 2016-07-12 01:36
Okey,i had solved this problem. Thank you.

**Comment by shelhamer** [comment] 2017-04-14 04:21
This was caused by the earlier multi-GPU edition of the tests fixed with the parallelism switch in #4563.

**Closed by shelhamer** 2017-04-14 04:21 UTC
