### ISSUE TITLE
MNIST Autoencoder Example hangs on data layer lock

### ISSUE THREAD

**Issue by andykitchen** [BVLC/caffe#3037] opened 2015-09-06 02:28 UTC
Hi, All

I'm running 5367a1af5dc8a56a284b7f1c67efce097871955a and running the mnist Autoencoder example just hangs. I have a very vanilla setup compiled on ubuntu 14.04 using cuda 7.0.

**Comment by andykitchen** [comment] 2015-09-06 02:34
the problem is not present in 8181870b9ac330a094ab0f8d53f54a0202f697a0 I'm using that version currently

**Comment by rdipietro** [comment] 2015-09-08 12:34
Same here. Curious: what Cuda Toolkit version are you using? I'm using 5.5, for which this older commit works out of the box (as opposed to having to throw away some multi-GPU code blocks in a C++ file with the following commits).

**Comment by nik-ko** [comment] 2015-09-16 14:19
I also can confirm this issue. 
Furthermore the MNIST autoencoder does not work with leveldb because the TRAIN datalayer locks train_lmdb.

**Comment by mohomran** [comment] 2015-09-16 18:36
A temporary workaround in this case would be to rename the source in the "test-on-train" data layer to:
> source: "./examples/mnist/mnist_train_lmdb"

vs. 

> source: "examples/mnist/mnist_train_lmdb"

The problem was introduced by the MultiGPU extension, particularly in bcc8f50a95ecad954d1887f3fb273eaa298e2274 partly as a result of lines 23-29 in data_reader.cpp:  
```C++
string key = source_key(param);
weak_ptr<Body>& weak = bodies_[key];
body_ = weak.lock();
if (!body_) {
  body_.reset(new Body(param));
  bodies_[key] = weak_ptr<Body>(body_);
}
```
Only one Body object is created per data source (the "key" being the path to the source/lmdb, hence the workaround), and for some reason this prevents the "test-on-train" data layer during setup from completing `Datum& datum = *(reader_.full().peek())`  in `DataLayer<Dtype>::DataLayerSetUp()`.

I have a rough patch that I could PR in, unless the people who were involved with that branch (@cypof, @ronghanghu) would prefer to take a crack at addressing it. Basically, it uses an additional layer parameter to override the "one Body per data source" restriction, but there's probably a more principled way to address this.

**Comment by andykitchen** [comment] 2015-09-17 05:41
@rdipietro I was using cuda 7.0, which was the newest at the time. 8181870b9ac330a094ab0f8d53f54a0202f697a0 compiles out of the box for me with CUDA 7.0

**Comment by mbz** [comment] 2015-10-30 17:26
I can confirm this bug as well. adding "./" to the source resolves the issue.

**Comment by seanbell** [comment] 2015-10-30 20:20
If using the path as a key, then perhaps the path should be made canonical.

**Comment by suruoxi** [comment] 2015-11-01 09:17
Same bug. And the "./" trick works.

**Comment by longjon** [comment] 2015-11-05 09:35
Closing in favor of #3108, which more directly explains the issue here.

**Closed by longjon** 2015-11-05 09:35 UTC
Labels: bug

**Comment by yinchuandong** [comment] 2016-03-23 00:05
Adding the "./" in "test-on-train" data layer works well. @mohomran Thank you very much.

**Comment by BobLiu20** [comment] 2017-03-18 01:10
Adding the "./" in "test-on-train" data layer works well. @mohomran Thank you very much.
