### ISSUE TITLE
libcaffe build issue about Nuget package(s)

### ISSUE THREAD

**Issue by gitxdf** [BVLC/caffe#4710] opened 2016-09-11 08:00 UTC
The issue is:
1>E:\deep-learning\caffe-windows\windows\libcaffe\libcaffe.vcxproj(379,5): error : This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\..\..\NugetPackages\OpenCV.2.4.10\build\native\OpenCV.props.

I am new, and dont know how to fix it. Please help me. Thx

**Comment by shelhamer** [comment] 2016-09-11 18:52
Duplicate of #4649.

**Closed by shelhamer** 2016-09-11 18:52 UTC
