### ISSUE TITLE
MAKE warning in layer_factory.cpp of "control reaches end of non-void function"

### ISSUE THREAD

**Issue by jgyllinsky** [BVLC/caffe#4719] opened 2016-09-12 22:37 UTC
Install seemed to work OK, but gcc gave the warning (via make) of `layer_factory.cpp:71:1: warning: control reaches end of non-void function [-Wreturn-type]`.

The file `layer_factory.cpp` is on github at [https://github.com/BVLC/caffe/blob/master/src/caffe/layer_factory.cpp](https://github.com/BVLC/caffe/blob/master/src/caffe/layer_factory.cpp)).

Building the CPU-Only version with OpenBLAS on Ubuntu 16.04lts (linux), having used the cmake method for generating the makefile.

```
$ make all
[  1%] Running C++/Python protocol buffer compiler on /opt/caffe/git/caffe-master/src/caffe/proto/caffe.proto
Scanning dependencies of target proto
[  1%] Building CXX object src/caffe/CMakeFiles/proto.dir/__/__/include/caffe/proto/caffe.pb.cc.o
[  3%] Linking CXX static library ../../lib/libproto-d.a
[  3%] Built target proto
Scanning dependencies of target caffe
[  3%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layer_factory.cpp.o
/opt/caffe/git/caffe-master/src/caffe/layer_factory.cpp: In function ‘boost::shared_ptr<caffe::Layer<Dtype> > caffe::GetConvolutionLayer(const caffe::LayerParameter&) [with Dtype = double]’:
/opt/caffe/git/caffe-master/src/caffe/layer_factory.cpp:71:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
/opt/caffe/git/caffe-master/src/caffe/layer_factory.cpp: In function ‘boost::shared_ptr<caffe::Layer<Dtype> > caffe::GetConvolutionLayer(const caffe::LayerParameter&) [with Dtype = float]’:
/opt/caffe/git/caffe-master/src/caffe/layer_factory.cpp:71:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
[  3%] Building CXX object src/caffe/CMakeFiles/caffe.dir/solvers/adadelta_solver.cpp.o
[  4%] Building CXX object src/caffe/CMakeFiles/caffe.dir/solvers/nesterov_solver.cpp.o

```
...

**Comment by shelhamer** [comment] 2016-09-12 23:25
Duplicate of #4703, to be resolved by that PR.

**Closed by shelhamer** 2016-09-12 23:25 UTC
