### ISSUE TITLE
Creating _caffe-d.pyd file instead of _caffe.pyd after installing Windows Caffe

### ISSUE THREAD

**Issue by hkjung00** [BVLC/caffe#5404] opened 2017-03-14 13:20 UTC
After installing the latest Windows Caffe with  **`USE_NCCL=1`** in **`build_win.cmd`**, it generates **`_caffe-d.pyd`** file in **`python/caffe`**  folder. As a consequence, when I type **`import caffe`**, it gives me the following errors:

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "C:\Users\KU_CVPR\Anaconda3\lib\site-packages\caffe\__init__.py", line 1, in <module>
>     from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
>   File "C:\Users\KU_CVPR\Anaconda3\lib\site-packages\caffe\pycaffe.py", line 13, in <module>
>     from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
> ImportError: No module named 'caffe._caffe'

After changing the file name from **`_caffe-d.pyd`** to **`_caffe.pyd`**, I successfully could use **`import caffe`**.
I wonder whether the above approach by changing the name is right or not.

The followings are my system environment and settings. 

### System configuration

> Operating system: Windows 10
> Compiler: Visual studio 2015 community
> CUDA version (if applicable): 8.0
> CUDNN version (if applicable): 5.1
> Python : Anaconda python 3.5

### Setting for build_win.cmd

> if NOT DEFINED MSVC_VERSION set MSVC_VERSION=14
> if NOT DEFINED WITH_NINJA set WITH_NINJA=1
> if NOT DEFINED CPU_ONLY set CPU_ONLY=0
> if NOT DEFINED CMAKE_CONFIG set CMAKE_CONFIG=Debug
> **if NOT DEFINED USE_NCCL set USE_NCCL=1**
> if NOT DEFINED CMAKE_BUILD_SHARED_LIBS set CMAKE_BUILD_SHARED_LIBS=0
> if NOT DEFINED PYTHON_VERSION set PYTHON_VERSION=3
> if NOT DEFINED BUILD_PYTHON set BUILD_PYTHON=1
> if NOT DEFINED BUILD_PYTHON_LAYER set BUILD_PYTHON_LAYER=1
> if NOT DEFINED BUILD_MATLAB set BUILD_MATLAB=0
> if NOT DEFINED PYTHON_EXE set PYTHON_EXE=python
> if NOT DEFINED RUN_TESTS set RUN_TESTS=0
> if NOT DEFINED RUN_LINT set RUN_LINT=0
> if NOT DEFINED RUN_INSTALL set RUN_INSTALL=0

**Comment by willyd** [comment] 2017-03-14 13:36
Change

`if NOT DEFINED CMAKE_CONFIG set CMAKE_CONFIG=Debug`
to 
`if NOT DEFINED CMAKE_CONFIG set CMAKE_CONFIG=Release`

If you really want a debug build then renaming the module is what I currently do.

**Comment by willyd** [comment] 2017-03-14 13:37
Works as intended. Closing.

**Closed by willyd** 2017-03-14 13:37 UTC

**Comment by willyd** [comment] 2017-03-14 14:02
Please not that NCCL has issues with the current windows branch. See #5400.
