### ISSUE TITLE
Shape mismatch error when resuming from snapshot

### ISSUE THREAD

**Issue by swamiviv** [BVLC/caffe#2697] opened 2015-07-05 17:18 UTC
I get the following error when I try to resume from a snapshot of my training:

```
I0705 13:12:21.277580 18337 solver.cpp:637] SGDSolver: restoring history
I0705 13:12:22.233752 18337 solver.cpp:294] Iteration 10000, Testing net (#0)
data
conv1
96 96
3 3
11 11
11 11
96 1
F0705 13:12:22.233953 18337 net.cpp:685] Check failed: target_blobs[j]->shape() == source_blob->shape() 
*** Check failure stack trace: ***
    @     0x7fd815fc7daa  (unknown)
    @     0x7fd815fc7ce4  (unknown)
    @     0x7fd815fc76e6  (unknown)
    @     0x7fd815fca687  (unknown)
    @     0x7fd81631f257  caffe::Net<>::ShareTrainedLayersWith()
    @     0x7fd8163fe856  caffe::Solver<>::Test()
    @     0x7fd8163ff206  caffe::Solver<>::TestAll()
    @     0x7fd8164080fb  caffe::Solver<>::Step()
    @     0x7fd816408acf  caffe::Solver<>::Solve()
    @           0x406887  train()
    @           0x404be1  main
    @     0x7fd8154d9ec5  (unknown)
    @           0x40520b  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)
```

The numbers printed there show where the mismatch is. These were printed from. Any ideas as to what's going on ? I am trying to finetune caffeNet for my task.

**Comment by seanbell** [comment] 2015-07-10 06:42
Did the net change or input data change between the snapshot and when you resumed?

**Comment by swamiviv** [comment] 2015-07-10 12:50
Neither has changed. It's a strange error. I can get around it if I do not
perform validation on my data. Only training the model works fine.

**Comment by longjon** [comment] 2015-07-13 07:21
Can you provide steps to reproduce this with the latest `master` in `DEBUG` mode? (See https://github.com/BVLC/caffe/wiki/Reporting-Bugs-and-Other-Issues.)

**Comment by shelhamer** [comment] 2017-04-14 01:51
Closing as irreproducible. My suspicion is that this was caused by changing the `group` setting as it alters the shape of the weights.

**Closed by shelhamer** 2017-04-14 01:51 UTC
