### ISSUE TITLE
Errors when run the example of "Fine-tuning CaffeNet"

### ISSUE THREAD

**Issue by RyanCV** [BVLC/caffe#4964] opened 2016-11-09 21:15 UTC
I have the following error when running the  example of "Fine-tuning CaffeNet of Style Recognition on “Flickr Style” Data. 
I run the following command at caffe root: `./build/tools/caffe train -solver models/finetune_flickr_style/solver.prototxt -weights models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel -gpu 0`.

The error is `data_transformer.cpp:520] Check failed: cv_cropped_image.rows == data_mean_.height() (227 vs. 256)`. 

How to solve it?

**Comment by williford** [comment] 2016-11-10 10:02
I tried reproducing your error, but I don't get any errors when I follow the instructions here:
http://caffe.berkeleyvision.org/gathered/examples/finetune_flickr_style.html

Please move the discussion to the Caffe user mailing list (closing this discussion). When you post, please give more steps so that others can reproduce it. Please also update to the latest BVLC/caffe branch, make clean, and redo the necessary steps. You can CC me at jonathan at neural dot vision, to make sure I see the message.

**Closed** 2016-11-10 15:06 UTC

**Comment by RyanCV** [comment] 2016-11-10 15:25
CC@jonathan, Hi, I have closed this discussion just now. However, I am not sure about what you said about "update to the latest BVLC/caffe brance". Do you mean I have to git clone the caffe into my machine again?
I run using GPU (K40, processor per nodes=16) this finetune_flickr_style example following the instructions step by step, however when I came to run the code 
`./build/tools/caffe train -solver models/finetune_flickr_style/solver.prototxt -weights models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel -gpu 0`, it gives me error which said 
`data_transformer.cpp:520] Check failed: cv_cropped_image.rows == data_mean_.height() (227 vs. 256)`. I have download the pretrained model and flickr dataset successfully, but it stuck at this fine tuning step. 
Is it clear for you to understand my question?

**Comment by williford** [comment] 2016-11-10 20:15
I understand your question, I just don't have enough information to reproduce your error.

Are you using Linux?

You seem to be using a different version of Caffe than the latest version from BVLC/caffe. The error message is thrown from the following line:
https://github.com/BVLC/caffe/blob/master/src/caffe/data_transformer.cpp#L520

If you look at the `solver.prototxt` you should see that the model is defined in `models/finetune_flickr_style/train_val.prototxt`. This will tell you that it is reading images of size 256x256 and the data transformation crops this to 227x227.

The error message is saying that `cv_cropped_image` has a height of 227, which is correct and `data_mean_` has a height of 256, which is also correct, because the mean file should be of the original size image. Newer versions of Caffe check to make sure that the `data_mean_` size is equal to the input image, see:
https://github.com/BVLC/caffe/blob/master/src/caffe/data_transformer.cpp#L386

What version of Caffe are you using? What do the following commands show:

    git remote -v
    git rev-parse HEAD

It should be relatively straightforward to clone BVLC/caffe again, copy your configuration file, and retrieve the data again.

**Comment by RyanCV** [comment] 2016-11-10 21:27
CC@jonathan, I updated the latest version of caffe, and now it works. Thanks for your help.

**Comment by nobody0702** [comment] 2017-04-17 07:23
I meet the same error, but don't know how to update
