### ISSUE TITLE
FCN run errors

### ISSUE THREAD

**Issue by ManyuChang** [BVLC/caffe#4570] opened 2016-08-10 08:41 UTC
I run FCN with the model. I clone FCN from https://github.com/shelhamer/fcn.berkeleyvision.org, and I download *.caffemodel. However, while running the coding, I face the following question:

Error parsing text-format caffe.NetParameter : 5 : 15: Message type " caffe.LayerParameter " has no field named "input_param",
WARNING: Logging before InitGoogleLogging() is written to STDERR.
F0810 16:28:47.643641 15677 upgrade_proto.cpp:928] Check failed: ReadProtoFromTestFile (param_file,param)  Failed to parse NetParameter file : voc-fcn8s/deploy.prototxt
*** Check failure stack trace: ***

How to solve this question?

**Comment by Lisandro79** [comment] 2016-08-23 05:28
Check #3947

**Comment by shelhamer** [comment] 2016-09-10 05:51
Duplicate of #3947. Please ask usage questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Closed by shelhamer** 2016-09-10 05:51 UTC

**Comment by wangzhaolei** [comment] 2017-03-22 07:31
@ManyuChang   dear manyu,I am a undergraduate form china, I have the same problem with you,but I can not resove it ,could you give me a cue about this question? Thank you very much!

**Comment by wangzhaolei** [comment] 2017-03-23 12:23
I have solved this problem.Here have two cause:1.need use the new caffe edition. I check the file:~/caffe/src/caffe/proto/caffe.proto   ,there  message LayerParameter has the InputParameter input_param = 143,ok! 2.in the python program  scripts,I write the sys.path.append  cafferoot+pathon

**Comment by nishathussain** [comment] 2017-05-22 11:38
[libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type "caffe.NetParameter" because it is missing required fields: layer[494].psroi_pooling_param.output_dim, layer[494].psroi_pooling_param.group_size
