### ISSUE TITLE
PyCaffe: slowdown of GPU acceleration (CPU is ok)

### ISSUE THREAD

**Issue by AleximusOrloff** [BVLC/caffe#6022] opened 2017-11-01 21:15 UTC
Hi all,
Using python module of Caffe I noticed that speed of forward pass depends on size of previous input

Code I run:
```python
h=512
w=512
im_data = np.empty([h, w, 3])
print(im_data.shape)
im_data = np.swapaxes(im_data, 0, 2)
im_data = np.array([im_data], dtype = np.float)
Net.blobs['data'].reshape(1, 3, w, h)
Net.blobs['data'].data[...] = im_data
k=0
while k<20:
        start_time = time.time()
        out = Net.forward()
        total_spend = total_spend + time.time() - start_time
        print "Total spend = %f, current spend = %f" %(total_spend,time.time() - start_time)
        k=k+1

h=16
w=16
im_data = np.empty([h, w, 3])
print(im_data.shape)
im_data = np.swapaxes(im_data, 0, 2)
im_data = np.array([im_data], dtype = np.float)
Net.blobs['data'].reshape(1, 3, w, h)
Net.blobs['data'].data[...] = im_data
k=0
while k<20:
        start_time = time.time()
        out = Net.forward()
        total_spend = total_spend + time.time() - start_time
        k=k+1
```

result CPU>>>
(512, 512, 3)
Total spend = 0.453633, current spend = 0.453639
Total spend = 0.611434, current spend = 0.157802
Total spend = 0.766412, current spend = 0.154979
Total spend = 0.920541, current spend = 0.154131
Total spend = 1.076776, current spend = 0.156237
Total spend = 1.231442, current spend = 0.154668
Total spend = 1.386451, current spend = 0.155010
Total spend = 1.540230, current spend = 0.153780
Total spend = 1.696707, current spend = 0.156478
Total spend = 1.853254, current spend = 0.156549
Total spend = 2.010661, current spend = 0.157408
Total spend = 2.166058, current spend = 0.155399
Total spend = 2.321408, current spend = 0.155352
Total spend = 2.476787, current spend = 0.155380
Total spend = 2.631135, current spend = 0.154350
Total spend = 2.786622, current spend = 0.155488
Total spend = 2.940805, current spend = 0.154185
Total spend = 3.096548, current spend = 0.155744
Total spend = 3.251005, current spend = 0.154458
Total spend = 3.406091, current spend = 0.155088
(16, 16, 3)
Total spend = 3.463368, current spend = 0.057279
Total spend = 3.463493, current spend = 0.000125
Total spend = 3.463600, current spend = 0.000107
Total spend = 3.463706, current spend = 0.000106
Total spend = 3.463817, current spend = 0.000112
Total spend = 3.463918, current spend = 0.000101
Total spend = 3.464019, current spend = 0.000100
Total spend = 3.464120, current spend = 0.000101
Total spend = 3.464220, current spend = 0.000100
Total spend = 3.464379, current spend = 0.000159
Total spend = 3.464515, current spend = 0.000136
Total spend = 3.464651, current spend = 0.000136
Total spend = 3.464751, current spend = 0.000101
Total spend = 3.464851, current spend = 0.000100
Total spend = 3.464952, current spend = 0.000101
Total spend = 3.465053, current spend = 0.000100
Total spend = 3.465153, current spend = 0.000100
Total spend = 3.465253, current spend = 0.000100
Total spend = 3.465353, current spend = 0.000100
Total spend = 3.465453, current spend = 0.000100

result GPU >>
(512, 512, 3)
Total spend = 0.024570, current spend = 0.024575
Total spend = 0.035578, current spend = 0.011011
Total spend = 0.046762, current spend = 0.011186
Total spend = 0.057938, current spend = 0.011177
Total spend = 0.068915, current spend = 0.010979
Total spend = 0.080003, current spend = 0.011089
Total spend = 0.090985, current spend = 0.010983
Total spend = 0.101882, current spend = 0.010898
Total spend = 0.112621, current spend = 0.010739
Total spend = 0.123411, current spend = 0.010790
Total spend = 0.134041, current spend = 0.010630
Total spend = 0.144658, current spend = 0.010617
Total spend = 0.155418, current spend = 0.010762
Total spend = 0.166558, current spend = 0.011141
Total spend = 0.177589, current spend = 0.011033
Total spend = 0.188786, current spend = 0.011199
Total spend = 0.200002, current spend = 0.011218
Total spend = 0.210893, current spend = 0.010892
Total spend = 0.221989, current spend = 0.011098
Total spend = 0.233669, current spend = 0.011682
(16, 16, 3)
Total spend = 0.251532, current spend = 0.017865
Total spend = 0.260617, current spend = 0.009086
Total spend = 0.269569, current spend = 0.008954
Total spend = 0.278521, current spend = 0.008953
Total spend = 0.287494, current spend = 0.008973
Total spend = 0.296458, current spend = 0.008965
Total spend = 0.305350, current spend = 0.008893
Total spend = 0.314149, current spend = 0.008799
Total spend = 0.322967, current spend = 0.008819
Total spend = 0.331809, current spend = 0.008844
Total spend = 0.341357, current spend = 0.009550
Total spend = 0.350171, current spend = 0.008816
Total spend = 0.359381, current spend = 0.009211
Total spend = 0.368544, current spend = 0.009164
Total spend = 0.377791, current spend = 0.009249
Total spend = 0.386919, current spend = 0.009129
Total spend = 0.395754, current spend = 0.008837
Total spend = 0.404894, current spend = 0.009143
Total spend = 0.413824, current spend = 0.008932
Total spend = 0.422858, current spend = 0.009035

**Comment by Noiredd** [comment] 2017-11-02 12:53
Closing as a good answer has been posted on the [duplicate of this question](https://groups.google.com/forum/#!topic/caffe-users/3BF9SmOfsoQ) on the caffe-users list (tl;dr: CPU-GPU communication takes so long that the speed gain from less computation is barely noticeable, also see [Amdahl's law](https://en.wikipedia.org/wiki/Amdahl%27s_law#Serial_programs)).

**Closed by Noiredd** 2017-11-02 12:53 UTC

**Comment by AleximusOrloff** [comment] 2017-11-02 13:08
I answered in those thread, and can answer here as well
when I run 16x16 -> 512x512 -> 16x16 on GPU
(16, 16, 3)
Total spend = 0.002017, current spend = 0.002021
Total spend = 0.003417, current spend = 0.001401
Total spend = 0.004847, current spend = 0.001430
Total spend = 0.006237, current spend = 0.001390
Total spend = 0.007648, current spend = 0.001411
Total spend = 0.009044, current spend = 0.001396
Total spend = 0.010410, current spend = 0.001367
Total spend = 0.011806, current spend = 0.001396
Total spend = 0.013251, current spend = 0.001445
Total spend = 0.014648, current spend = 0.001397
Total spend = 0.016019, current spend = 0.001372
Total spend = 0.017364, current spend = 0.001345
Total spend = 0.018638, current spend = 0.001274
Total spend = 0.019908, current spend = 0.001271
Total spend = 0.021204, current spend = 0.001296
Total spend = 0.022452, current spend = 0.001249
Total spend = 0.023756, current spend = 0.001305
Total spend = 0.025046, current spend = 0.001291
Total spend = 0.026302, current spend = 0.001256
Total spend = 0.027593, current spend = 0.001291
(512, 512, 3)
Total spend = 0.056869, current spend = 0.029278
Total spend = 0.067891, current spend = 0.011024
Total spend = 0.079106, current spend = 0.011217
Total spend = 0.090121, current spend = 0.011016
Total spend = 0.100846, current spend = 0.010727
Total spend = 0.111873, current spend = 0.011029
Total spend = 0.123058, current spend = 0.011187
Total spend = 0.134164, current spend = 0.011107
Total spend = 0.145391, current spend = 0.011228
Total spend = 0.156205, current spend = 0.010816
Total spend = 0.167113, current spend = 0.010909
Total spend = 0.177855, current spend = 0.010742
Total spend = 0.188745, current spend = 0.010890
Total spend = 0.199293, current spend = 0.010548
Total spend = 0.209808, current spend = 0.010516
Total spend = 0.220464, current spend = 0.010659
Total spend = 0.232250, current spend = 0.011788
Total spend = 0.243037, current spend = 0.010787
Total spend = 0.253932, current spend = 0.010896
Total spend = 0.264904, current spend = 0.010974
(16, 16, 3)
Total spend = 0.282079, current spend = 0.017176
Total spend = 0.291167, current spend = 0.009090
Total spend = 0.300439, current spend = 0.009272
Total spend = 0.309566, current spend = 0.009128
Total spend = 0.318727, current spend = 0.009162
Total spend = 0.327840, current spend = 0.009114
Total spend = 0.336762, current spend = 0.008923
Total spend = 0.345607, current spend = 0.008846
Total spend = 0.354512, current spend = 0.008905
Total spend = 0.363403, current spend = 0.008892
Total spend = 0.372276, current spend = 0.008874
Total spend = 0.381008, current spend = 0.008732
Total spend = 0.389814, current spend = 0.008806
Total spend = 0.398521, current spend = 0.008708
Total spend = 0.407293, current spend = 0.008774
Total spend = 0.417090, current spend = 0.009799
Total spend = 0.426105, current spend = 0.009016
Total spend = 0.435250, current spend = 0.009146
Total spend = 0.444297, current spend = 0.009049
Total spend = 0.453480, current spend = 0.009184


i.e, first 16x16 passes significantly faster than last ones!
