### ISSUE TITLE
python layer error：MemoryError

### ISSUE THREAD

**Issue by janicevidal** [BVLC/caffe#6291] opened 2018-03-15 08:25 UTC
### Issue summary
![_20180315_111313](https://user-images.githubusercontent.com/29887681/37450752-28cc58cc-286a-11e8-8ee1-b293b6a41188.png)

python layer error：MemoryError , boost or proto issues?

**Comment by twmht** [comment] 2018-03-16 04:57
@janicevidal 

can you share minimal prototxt which can reproduce your problem?

**Comment by janicevidal** [comment] 2018-03-19 01:40
# # @twmht 

layer {
    name: "hdf5_train_data"
    type: "HDF5Data"
    top: "data"
    top: "X"
    include {
        phase: TRAIN
    }
    hdf5_data_param {
        source: "train.txt"
        batch_size: 64
    }
}
layer {
    name: "hdf5_test_data"
    type: "HDF5Data"
    top: "data"
    top: "X"
    include {
        phase: TEST
    }
    hdf5_data_param {
        source: "test.txt"
        batch_size: 64
    }
}

layer {
    name: "Conv1"
    type: "Convolution"
    bottom: "data"
    top: "Conv1"
    param {
        lr_mult: 1
        decay_mult: 1
    }
    param {
        lr_mult: 2
        decay_mult: 0
    }
    convolution_param {
        num_output: 16
        pad: 2
        kernel_size: 5
        stride: 1
        weight_filler {
            type: "xavier"
            std: 0.1
        }
        bias_filler {
            type: "constant"
            value: 0.2
        }
    }
}

layer {
  name: "ActivationTangH1"
  bottom: "Conv1"
  top: "ActivationTangH1"
  type: "TanH"
}

layer {
  name: "ActivationAbs1"
  bottom: "ActivationTangH1"
  top: "Abs1"
  type: "AbsVal"
}

layer {
    name: "Pool1"
    type: "Pooling"
    bottom: "Abs1"
    top: "Pool1"
    pooling_param {
        pool: MAX
        kernel_size: 2
        stride: 2
    }
}

layer {
    name: "Conv2"
    type: "Convolution"
    bottom: "Pool1"
    top: "Conv2"
    param {
        lr_mult: 1
        decay_mult: 1
    }
    param {
        lr_mult: 2
        decay_mult: 0
    }
    convolution_param {
        num_output: 48
        pad: 1
        kernel_size: 3
        stride: 1
        weight_filler {
        type: "xavier"
        std: 0.1
    }
    bias_filler {
        type: "constant"
        value: 0.2
        }
    }
}

layer {
  name: "ActivationTangH2"
  bottom: "Conv2"
  top: "ActivationTangH2"
  type: "TanH"
}

layer {
  name: "ActivationAbs2"
  bottom: "ActivationTangH2"
  top: "Abs2"
  type: "AbsVal"
}


layer {
    name: "Pool2"
    type: "Pooling"
    bottom: "Abs2"
    top: "Pool2"
    pooling_param {
        pool: MAX
        kernel_size: 2
        stride: 2
    }
}

# layer 3
layer {
    name: "Conv3"
    type: "Convolution"
    bottom: "Pool2"
    top: "Conv3"
    param {
        lr_mult: 1
        decay_mult: 1
    }
    param {
        lr_mult: 2
        decay_mult: 0
    }
    convolution_param {
        num_output: 64
        pad: 0
        kernel_size: 3
        stride: 1
        weight_filler {
            type: "xavier"
            std: 0.1
        }
        bias_filler {
            type: "constant"
            value: 0.2
        }
    }
}


layer {
  name: "ActivationTangH3"
  bottom: "Conv3"
  top: "ActivationTangH3"
  type: "TanH"
}

layer {
  name: "ActivationAbs3"
  bottom: "ActivationTangH3"
  top: "Abs3"
  type: "AbsVal"
}

layer {
    name: "Pool3"
    type: "Pooling"
    bottom: "Abs3"
    top: "Pool3"
    pooling_param {
        pool: MAX
        kernel_size: 3
        stride: 2
    }
}

# layer 4
layer {
    name: "Conv4"
    type: "Convolution"
    bottom: "Pool3"
    top: "Conv4"
    param {
        lr_mult: 1
        decay_mult: 1
    }
    param {
        lr_mult: 2
        decay_mult: 0
    }
    convolution_param {
        num_output: 64
        pad: 0
        kernel_size: 2
        stride: 1
        weight_filler {
            type: "xavier"
            std: 0.1
        }
        bias_filler {
            type: "constant"
            value: 0.2
        }
    }
}


layer {
  name: "ActivationTangH4"
  bottom: "Conv4"
  top: "ActivationTangH4"
  type: "TanH"
}

layer {
  name: "ActivationAbs4"
  bottom: "ActivationTangH4"
  top: "Abs4"
  type: "AbsVal"
}

layer {
    name: "Dense1"
    type: "InnerProduct"
    bottom: "Abs4"
    top: "Dense1"
    param {
        lr_mult: 1
        decay_mult: 1
    }
    param {
        lr_mult: 2
        decay_mult: 0
    }
    inner_product_param {
        num_output: 100
        weight_filler {
            type: "xavier"
        }
        bias_filler {
            type: "constant"
            value: 0
        }
    }
}


layer {
  name: "ActivationTangH5"
  bottom: "Dense1"
  top: "ActivationTangH5"
  type: "TanH"
}

layer {
  name: "ActivationAbs5"
  bottom: "ActivationTangH5"
  top: "Abs5"
  type: "AbsVal"
}


layer {
    name: "Dense2"
    type: "InnerProduct"
    bottom: "Abs5"
    top: "Dense2"
    param {
        lr_mult: 1
        decay_mult: 1
    }
    param {
        lr_mult: 2
        decay_mult: 0
    }
    inner_product_param {
        num_output: 10
        weight_filler {
            type: "xavier"
        }
        bias_filler {
            type: "constant"
            value: 0
        }
    }
}

layer {
  type: 'Python'
  name: 'loss'
  top: 'loss'
  bottom: 'Dense2'
  bottom: 'X'
  python_param {
    module: 'NormlizedMSE'
    layer: 'EuclideanLossLayer'
  }
  loss_weight: 1
}

**Comment by Noiredd** [comment] 2018-03-19 10:47
Is this really a minimal example? Minimal means: removing just one layer from this network will make the issue go away. Can you produce an example in which your Python layer takes just two `input` blobs and still throws an error?  
Please also attach the code of the layer itself.

**Comment by janicevidal** [comment] 2018-03-19 12:21
@Noiredd 
Sorry！the training process will be normal when the loss layer is usual EuclideanLoss，but,  any layer written by python layer , as input layer or loss layer, will produce this errror. The network is tiny with  small batchsize , it can not produce memory error usually.

**Comment by twmht** [comment] 2018-03-19 12:25
@janicevidal 

so this issue may not be related to caffe. you should provide the implementation of the custom loss layer.

**Comment by Noiredd** [comment] 2018-08-17 12:52
Closing due to lack of updates. Feel free to reopen when you complete the details requested in the previous post.

**Closed by Noiredd** 2018-08-17 12:52 UTC
