### ISSUE TITLE
CUBLAS_STATUS_SUCCESS(1 VS.0)CUBLAS_NOT_INITALIZATION

### ISSUE THREAD

**Issue by SHUht** [BVLC/caffe#5564] opened 2017-04-25 13:08 UTC
I built a deep learning server. I used NVIDIA GPU 1080Ti ,ubuntu16.04 ,CUDA8.0 ,caffe. I have succeeded in making runtest caffe. However, when I tested the mnist example,a problem appeared.

Check failed: status ==CUBLAS_STATUS_SUCCESS(1 VS.0)CUBLAS_NOT_INITALIZATION
*** Check failure stack trace: ***
      @             0x7f2913a0e5cd  google::LogMessage::Fail( )

who can help me? Please tell me the reason why appear the issue and how to solve the problem.
Thanks very  #much!
![Uploading IMG_1200.JPG…]()

_

**Comment by bear63** [comment] 2017-10-31 03:03
sudo rm -rf .nv/

https://devtalk.nvidia.com/default/topic/1007071/cuda-setup-and-installation/cuda-error-when-running-matrixmulcublas-sample-ubuntu-16-04/

**Comment by Noiredd** [comment] 2018-02-23 13:09
I suggest following the [thread](https://devtalk.nvidia.com/default/topic/1007071/cuda-setup-and-installation/cuda-error-when-running-matrixmulcublas-sample-ubuntu-16-04/) linked by @bear63 before doing that `rm`.

I will close the issue for now, but feel free to reopen if the error persists. However I don't think this issue is caused by Caffe itself - more like a CUDA installation or driver problem.

**Closed by Noiredd** 2018-02-23 13:09 UTC

**Comment by sobolevhuang** [comment] 2019-04-26 08:38
In win10 system I met the same problem,  Check failed: status == CUDNN_STATUS_SUCCESS (1 vs. 0)  CUDNN_STATUS_NOT_INITIALIZED, but I used the NVIDIA GeForce GT 720M  CUDA7.5，whether I should choose a better machine?
