### ISSUE TITLE
Inconsistency in output shape calculation between convolution and pooling layers

### ISSUE THREAD

**Issue by serg14** [BVLC/caffe#4773] opened 2016-09-25 21:23 UTC
In the scenario when input_dim=10, kernel_size=3, pad=0, stride=2, convolution layer gives an output dim of 4, while pooling layer gives 5. The problem is that output shape is computed differently:

conv_layer.cpp(18):
`const int output_dim = (input_dim + 2 * pad_data[i] - kernel_extent) / stride_data[i] + 1;`

pooling_layer.cpp(90):
`pooled_height_ = static_cast<int>(ceil(static_cast<float>( height_ + 2 * pad_h_ - kernel_h_) / stride_h_)) + 1;`

Overall not a big deal, but still ugly, e.g. in the fully conv network if one wants to concatenate strided pooling and convolution outputs.

**Comment by shelhamer** [comment] 2016-09-27 19:36
Duplicate of #1318. This is a common duplicate—please remember to search past issues. I agree these should be reconciled at some point, but we need to keep the old behavior an optional for backward compatibility.

**Closed by shelhamer** 2016-09-27 19:36 UTC
